name: Plugin Icon Request
description: Request an icon for your verified plugin
title: "Plugin Icon Request"
body:
  - type: markdown
    attributes:
      value: |
        Icons can only be request by the developer of the verified plugin. Please ensure that it will not violate any trademark or licensing agreements.
  - type: input
    attributes:
      label: Link To NPM Package
      placeholder: https://www.npmjs.com/package/homebridge-xyz
    validations:
      required: true
  - type: textarea
    attributes:
      label: Plugin Icon
      description: Please attach the icon you would like to use. This must be a square image, around 100px by 100px, and in PNG format.
    validations:
      required: true
