name: Plugin Review Request
description: Request your plugin be reviewed for verification
title: "homebridge-"
labels: [pending-review]
body:
  - type: markdown
    attributes:
      value: |
        Please double check the [requirements list](https://github.com/homebridge/verified#requirements) before submitting a request. Please ensure that any icon will not violate any trademark or licensing agreements.
  - type: input
    attributes:
      label: Link To GitHub Repo
      placeholder: https://github.com/homebridge/homebridge-xyz
    validations:
      required: true
  - type: input
    attributes:
      label: Link To NPM Package
      placeholder: https://www.npmjs.com/package/homebridge-xyz
    validations:
      required: true
  - type: textarea
    attributes:
      label: Plugin Icon (Optional)
      description: Please attach the icon you would like to use. This must be a square image, around 100px by 100px, and in PNG format.
    validations:
      required: false
