name: Validate JSON

on:
  push:
    branches: [latest]
  pull_request:
    branches: [latest]

jobs:
  check-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cat verified-plugins.json | jq type
      - run: cat plugin-icons.json | jq type
