name: Validate JSON

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cat verified-plugins.json | jq type
