name: Plugin Pre-Checks

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  check-plugin:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' || (github.event_name == 'issue_comment' && github.event.comment.body == '/check')
    steps:
      - uses: actions/checkout@v1

      - name: Install Dependencies
        run: npm install --prefix precheck

      - name: Check Plugin
        uses: './precheck'
