name: Stale Workflow
on:
  workflow_dispatch: null
  schedule:
    - cron: 45 11 * * *
jobs:
  stale:
    uses: homebridge/.github/.github/workflows/stale.yml@latest
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
